install.packages("tidyverse", repos = "http://cran.us.r-project.org")
install.packages("devtools", repos = "http://cran.us.r-project.org")
# devtools::install_github("teramonagi/fitbitr")
install.packages("ggthemes", repos = "http://cran.us.r-project.org")
install.packages("scales", repos = "http://cran.us.r-project.org")
install.packages("lubridate", repos = "http://cran.us.r-project.org")
# install.packages("PerformanceAnalytics")
