install.packages("dplyr", repos = "http://cran.us.r-project.org", dependencies=TRUE)
install.packages("tidyverse", repos = "http://cran.us.r-project.org", dependencies=TRUE)
install.packages("devtools", repos = "http://cran.us.r-project.org", dependencies=TRUE)
# devtools::install_github("teramonagi/fitbitr")
install.packages("ggthemes", repos = "http://cran.us.r-project.org", dependencies=TRUE)
install.packages("scales", repos = "http://cran.us.r-project.org", dependencies=TRUE)
install.packages("lubridate", repos = "http://cran.us.r-project.org", dependencies=TRUE)
# install.packages("PerformanceAnalytics")
